import type { Metadata } from "next"
import { Inter as FontSans } from "next/font/google"
import "./globals.css"
import { cn } from "@/lib/utils"
import AuthContext from "@/components/auth-context"
import ThemeProvider from "@/components/theme-provider"
import HolyLoader from "holy-loader"
import { Toaster } from "@/components/ui/toaster"

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
  display: "swap",
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={cn("h-full font-sans antialiased", fontSans.variable)}>
        <HolyLoader
          color="#ff4500"
          height="4px"
          speed={250}
          easing="linear"
          showSpinner
        />
        <ThemeProvider attribute="class" defaultTheme="light" enableSystem>
          <AuthContext>
            <div className="h-full">{children}</div>
          </AuthContext>
          <Toaster />
        </ThemeProvider>
      </body>
    </html>
  )
}
