import Layout from '@/components/layout/Layout';
import localFont from 'next/font/local';
import './globals.css';
import { Inter as FontSans } from 'next/font/google';
import AuthContext from '@/components/context/AuthContext';
import Provider from '@/components/context/Provider';
import { cn } from '@/lib/cn';

const fontSans = FontSans({
  subsets: ['latin'],
  variable: '--font-sans',
});

// Font files can be colocated inside of `pages`
const fontHeading = localFont({
  src: '../assets/fonts/CalSans-SemiBold.woff2',
  variable: '--font-heading',
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={cn(
          'font-sans bg-background antialiased h-full min-h-screen overflow-x-hidden',
          fontSans.variable,
          fontHeading.variable
        )}
      >
        <Provider>
          <AuthContext>{children}</AuthContext>
        </Provider>
      </body>
    </html>
  );
}
